### DISCUSSION TITLE
New Script Suggestion: CodeProject.AI

### DISCUSSION THREAD

**Discussion by xijio** [tteck/Proxmox#1066] [Ideas]
https://hub.docker.com/r/codeproject/ai-server

https://www.codeproject.com/Articles/5322557/CodeProject-AI-Server-AI-the-easy-way

This is an open source AI object detection engine, a re-write of the abandoned deepstack. It's frequently used in companion to Blue Iris as the server for smart object detection for home security footage.  I currently have it installed in a docker lxc, but would be awesome to have it's own script.

**Comment by lightmaster** [comment]
Would love to see this. I ended up creating a Docker LXC and installing CodeProject.AI Server in that instance of Docker. I'm sure there's some loss of performance due to the nesting there, but better than setting it up in a VM. Would be awesome to get a script that sets CodeProject.AI up directly inside a LXC

**Reply by Yonny24** [reply]
Did you get CPAI working as an lxc on proxmox? I've tried several times, it's running but not working 100%

Testing any image just gets queued and not processed.
Any ideas?

Are you running it on a debian or ubuntu lxc? Unprivileged with host network?

Thanks

**Reply by lightmaster** [reply]
Sorry it took me so long to respond, I never get any emails from github about responses or anything.

So I have CPAI running as a Debian 12 LXC. I used the Docker LXC template, selecting Debian 12 and for it to be Privileged. I gave it 8 CPU cores, 4GB RAM, and 20GB SSD. I also have Nesting enabled (pretty sure template did that). Then I used Portainer to create a new Stack, using the below docker-compose.yml. I specify the tag number so that I know it won't ever pull an update unless I want it updated (got burned twice by bad updates that just didn't work).

I also have custom models installed to `/opt/codeproject/custom-models/YOLOv5-6.2, downloaded from [https://github.com/MikeLud/CodeProject.AI-Custom-IPcam-Models/tree/main/PT%20Models](https://github.com/MikeLud/CodeProject.AI-Custom-IPcam-Models/tree/main/PT%20Models)

In my router, I have a DHCP reservation setup for the LXC as `codeproject-ai`, so that I can run `ping codeproject-ai` from Windows Powershell on my BI server (or you could just use the IP instead of the hostname). Then I have BI setup to use the AI server on `codeproject-ai` and port `32168` and a timeout of 15s. Make sure to uncheck "Auto start/stop with BI". If you want to use custom models, check that option. I have my cameras set to search for `person,bicycle,vehicle,car,motorcycle,bus,truck,cat,dog,deer` to confirm in Camera > Ai Settings

```yaml
version: "3.9"

services:
  CodeProject.AI-Server:
    image: codeproject/ai-server:cpu-2.5.4
    container_name: CodeProject.AI-Server
    volumes:
      - /opt/codeproject/custom-models/YOLOv5-6.2:/app/preinstalled-modules/ObjectDetectionYOLOv5-6.2/custom-models
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York
    ports:
      - 32168:32168/tcp
    restart: unless-stopped
```

Then, when the Docker LXC is running and CPAI is running inside Portainer, you can go to http://IP:32168 in a browser and should see the interface, with the count ticking up on YOLOv5 6.2 whenever BI sends an image to it.

**Reply by xijio** [reply]
Also working for me.  I used the docker lxc and here is my docker-compose.yml:


```yaml
version: "3.9"

services:
  CodeProjectAI:
    image: codeproject/ai-server:cuda11_7
    container_name: codeproject-ai-server-cuda
    hostname: codeproject-ai-server
    restart: unless-stopped
    ports:
      - "32168:32168"
    environment:
      - TZ=America/Los_Angeles
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

I used this guide for getting the nvidia gpu inside: https://jocke.no/2022/02/23/plex-gpu-transcoding-in-docker-on-lxc-on-proxmox/
