### DISCUSSION TITLE
Zigbee2MQTT LXC - Error: Resource temporarily unavailable Cannot lock port

### DISCUSSION THREAD

**Discussion by EricSnijders** [tteck/Proxmox#1390] [Help Needed] [answered]
I have no idea what's going on. I just deployed the the LXC. Everything was working fine. Then i went over and changed the network adapter within Proxmox from DHCP to static. Rebooted the LXC and now it can't use my Sonoff Zigbee Stick anymore...

Proxmox Shell:
```
root@proxmox:~# ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 May  4 12:58 usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0 -> ../../ttyUSB0
```

Zigbee2MQTT LXC shell:
```
root@zigbee2mqtt:/opt/zigbee2mqtt# ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 May  4 12:58 usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0 -> ../../ttyUSB0
```

Configuration.yaml on Zigbee2MQTT LXC:
```
root@zigbee2mqtt:/opt/zigbee2mqtt# cat ./data/configuration.yaml 
frontend:
  port: 9442
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.5.200:1883
  user: Someone
  password: SomethingSomething
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
advanced:
  pan_id: 9291
  network_key:
    - 159
    - 239
    - 158
    - 96
    - 121
    - 39
    - 192
    - 249
    - 50
    - 117
    - 243
    - 245
    - 177
    - 139
    - 107
    - 205
  channel: 20
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xb4e3f9fffec035e5':
    friendly_name: Dressoir
  '0xb4e3f9fffeaab78d':
    friendly_name: Lantaarn
  '0xb4e3f9fffebc1c31':
    friendly_name: Vrij01
```

`dmesg` on the LXC shows:
```
[14795.112822] usb 1-9: new full-speed USB device number 6 using xhci_hcd
[14795.262644] usb 1-9: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[14795.262646] usb 1-9: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[14795.262648] usb 1-9: Product: Sonoff Zigbee 3.0 USB Dongle Plus
[14795.262649] usb 1-9: Manufacturer: Silicon Labs
[14795.262650] usb 1-9: SerialNumber: 0001
[14795.264052] cp210x 1-9:1.0: cp210x converter detected
[14795.266875] usb 1-9: cp210x converter now attached to ttyUSB0
```

I also tried `/dev/ttyUSB0` in my configuration.yaml but it gives me the same error.
And running `ls -l /proc/[0-9]/fd/ |grep /dev/ttyUSB0` gives me 0 results as well.
