### DISCUSSION TITLE
Zigbee2MQTT LXC - will not start 'ioctl errors'

### DISCUSSION THREAD

**Discussion by bearhntr** [tteck/Proxmox#1556] [Help Needed]
@tteck , 

  Again - much thanks for your scripts.  I have gotten so far HAOS VM running, with MariaDB in an LXC container (still questioning if I should have put HA in an LXC (you thoughts?)) - I next did two more LXC (one for MQTT and one for Zigbee2MQTT), and here is where I am stopped.

  I followed your steps, and created the _configuration.yaml_ file - set the User and Pass which I setup when I installed MQTT, and set the IP as the DHCP reservation is set for the LXC and have set the _port:_ identifier per your steps.  I get the following when I launch things:

```
root@zigbee2mqtt:~# cd /opt/zigbee2mqtt && npm start

> zigbee2mqtt@1.31.2 start
> node index.js

Building Zigbee2MQTT... (initial build), finished
Zigbee2MQTT:info  2023-06-27 20:46:45: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-06-27.20-46-45' filename: log.txt
Zigbee2MQTT:info  2023-06-27 20:46:45: Starting Zigbee2MQTT version 1.31.2 (commit #21f51258)
Zigbee2MQTT:info  2023-06-27 20:46:45: Starting zigbee-herdsman (0.14.117)
Zigbee2MQTT:error 2023-06-27 20:46:45: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-06-27 20:46:45: Failed to start zigbee
Zigbee2MQTT:error 2023-06-27 20:46:45: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-06-27 20:46:45: Exiting...
Zigbee2MQTT:error 2023-06-27 20:46:45: Error: Error while opening serialport 'Error: Error: Inappropriate ioctl for device setting custom baud rate of 115200'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:75:22)
    at /opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:111:18
root@zigbee2mqtt:/opt/zigbee2mqtt# cd /opt/zigbee2mqtt && npm start
```
What did I do wrong?

**Comment by tteck** [comment]
Post your `configuration.yaml`

**Reply by bearhntr** [reply]
```
frontend:
  port: 9442
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt.bearcave-home.com:1883
  user: bearcavehome
  password: {removed_for_security}
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_f6cac5fea612ec11841b23c7bd930c07-if00-port0
  #port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0  #Original Line from sample
  #adapter: deconz      #(uncomment for ConBee II)
  #adapter: ezsp    #(uncomment for ITead Sonoff Zigbee 3.0 USB Dongle Plus V2 model "ZBDongle-E version")
advanced:
  pan_id: GENERATE
  network_key: GENERATE
  channel: 20
```
and here is the output from the [ ls -l /dev/serial/by-id ] command:

```root@zigbee2mqtt:/opt/zigbee2mqtt# ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Jun 27 21:31 usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_f6cac5fea612ec11841b23c7bd930c07-if00-port0 -> ../../ttyUSB0
```

**Comment by tteck** [comment]
https://smarthomescene.com/guides/how-to-separate-zigbee2mqtt-from-home-assistant-in-proxmox/

**Reply by bearhntr** [reply]
Tried this too - no such luck (using Method B)

**Comment by tteck** [comment]
Look over the corrections that I suggest

```
frontend:
  port: 9442
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://10.9.28.243:1883' 
  user: bearcavehome
  password: pwd
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_f6cac5fea612ec11841b23c7bd930c07-if00-port0
  baudrate: 115200
  rtscts: false
advanced:
  pan_id: GENERATE
  network_key: GENERATE
  channel: 20
```
edit

**Reply by tteck** [reply]
Update the `configuration.yaml` with the MQTT LXC IP and your password. Reboot the Z2M LXC 
See if the frontend is available at <Z2M IP>:9442

**Reply by bearhntr** [reply]
Here is what I have now:
```
frontend:
  port: 9442
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://10.9.28.243:1883'
  user: bearcavehome
  password: <pwd>
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_f6cac5fea612ec11841b23c7bd930c07-if00-port0
advanced:
  pan_id: GENERATE
  network_key: GENERATE
  channel: 20
```

restarted the LXC and then ran start command - and I get:

```
Last login: Tue Jun 27 21:36:08 EDT 2023 on tty1
root@zigbee2mqtt:~# cd /opt/zigbee2mqtt && npm start

> zigbee2mqtt@1.31.2 start
> node index.js

Zigbee2MQTT:info  2023-06-27 22:14:13: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-06-27.22-14-13' filename: log.txt
Zigbee2MQTT:info  2023-06-27 22:14:13: Starting Zigbee2MQTT version 1.31.2 (commit #21f51258)
Zigbee2MQTT:info  2023-06-27 22:14:13: Starting zigbee-herdsman (0.14.117)
Zigbee2MQTT:error 2023-06-27 22:14:14: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-06-27 22:14:14: Failed to start zigbee
Zigbee2MQTT:error 2023-06-27 22:14:14: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-06-27 22:14:14: Exiting...
Zigbee2MQTT:error 2023-06-27 22:14:14: Error: Error while opening serialport 'Error: Error: Inappropriate ioctl for device setting custom baud rate of 115200'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:75:22)
    at /opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:111:18
root@zigbee2mqtt:/opt/zigbee2mqtt# 

```

**Reply by bearhntr** [reply]
![image](https://github.com/tteck/Proxmox/assets/100164602/8acf8a9b-9bef-447d-9421-ec2b5500d29a)

**Reply by bearhntr** [reply]
I have even tried 8080 for the port - I get same error.  Because Z2M does not start.

**Reply by tteck** [reply]
Does the `pan_id:` and `network_key:` still say `GENERATE`?

**Reply by bearhntr** [reply]
![image](https://github.com/tteck/Proxmox/assets/100164602/34b5e0c0-a2a9-494c-87fa-a087426b7a01)

**Reply by bearhntr** [reply]
![image](https://github.com/tteck/Proxmox/assets/100164602/dc968e52-604f-4f21-998b-8b076985fbb0)

**Reply by bearhntr** [reply]
MQTT = 10.9.28.243
Z2M = 10.9.28.244

**Reply by tteck** [reply]
I don't understand this `Error: Error while opening serialport 'Error: Error: Inappropriate ioctl for device setting custom baud rate of 115200'`

**Reply by tteck** [reply]
I updated the `configuration.yaml` above (https://github.com/tteck/Proxmox/discussions/1556#discussioncomment-6299609) try it, just reboot the LXC, do not start manually.

**Reply by bearhntr** [reply]
OK  -  Copied yours and added back my PW rebooted LXC.  I get the following in browser.

![image](https://github.com/tteck/Proxmox/assets/100164602/15c1afa6-59e4-417e-89c9-785f74a662fd)

**Reply by tteck** [reply]
same error?

**Reply by tteck** [reply]
Z2M is a Debian 11 LXC, correct?

**Reply by tteck** [reply]
Does the `pan_id:` and `network_key:` still say GENERATE?

**Reply by bearhntr** [reply]
Yes..  Browser gives same error -- if I try and manually start I get:
```
root@zigbee2mqtt:/opt/zigbee2mqtt# cd /opt/zigbee2mqtt && npm start

> zigbee2mqtt@1.31.2 start
> node index.js

Zigbee2MQTT:info  2023-06-27 22:47:00: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-06-27.22-47-00' filename: log.txt
Zigbee2MQTT:info  2023-06-27 22:47:00: Starting Zigbee2MQTT version 1.31.2 (commit #21f51258)
Zigbee2MQTT:info  2023-06-27 22:47:00: Starting zigbee-herdsman (0.14.117)
Zigbee2MQTT:error 2023-06-27 22:47:01: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-06-27 22:47:01: Failed to start zigbee
Zigbee2MQTT:error 2023-06-27 22:47:01: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-06-27 22:47:01: Exiting...
Zigbee2MQTT:error 2023-06-27 22:47:01: Error: Error while opening serialport 'Error: Error: Inappropriate ioctl for device setting custom baud rate of 115200'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:75:22)
    at /opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:111:18
root@zigbee2mqtt:/opt/zigbee2mqtt# 
```

I can find nothing which makes sense for the  **'Error: Error: Inappropriate ioctl for device setting custom baud rate of 115200'**

**Reply by bearhntr** [reply]
Yes - Ran your script - with dongle plugged in and chose defaults - until the end (about EDGE) and chose 'N'

**Reply by tteck** [reply]
As a last resort, try changing to this `baudrate: 57600`

**Reply by tteck** [reply]
> The specific error "Inappropriate ioctl for device" suggests that the ioctl (input/output control) operation used to set the baud rate is not supported or allowed by the device.

Have you changed the firmware?

**Reply by bearhntr** [reply]
Firmware which came on it.  Works perfectly fine in my other HA box with the ZHA stuff.

**Reply by tteck** [reply]
Update to the newest firmware, that will clear everything on the dongle.

**Comment by bearhntr** [comment]
> Does the `pan_id:` and `network_key:` still say GENERATE?
```
advanced:
  pan_id: GENERATE
  network_key: GENERATE
  channel: 20
```
