### DISCUSSION TITLE
Debian VM w/ Static IP

### DISCUSSION THREAD

**Discussion by Trblz42** [tteck/Proxmox#2284] [Help Needed]
I've installed a Debian 12 VM using the helper script https://github.com/tteck/Proxmox/raw/main/vm/debian-vm.sh 
The intent is to use this VM as a Pihole-Unbound-Gravity setup so a fixed IP is needed.
I can set a DHCP reservation in my router to achieve the same goal but for a DNS server i dont want this.

The usual tools like nmcli, /etc/network/interfaces, cloudinit are all not working.  What step am i missing? 

> root@localhost:~# hostnamectl
>    Static hostname: (unset)                          
> Transient hostname: localhost
>          Icon name: computer-vm
>            Chassis: vm 🖴
>         Machine ID: 
>            Boot ID: 
>     Virtualization: kvm
>   Operating System: Debian GNU/Linux 12 (bookworm)   
>             Kernel: Linux 6.1.0-16-amd64
>       Architecture: x86-64
>    Hardware Vendor: QEMU
>     Hardware Model: Standard PC _i440FX + PIIX, 1996_
>   Firmware Version: 4.2023.08-2

**Comment by nmorgowicz** [comment]
Surprisingly a lot of docs/guides are incorrect with debian 12 networking. It uses netplan.

Get your ethernet adapter name via: ip addr

Then you can set a static ip by editing /etc/netplan/90-default.yaml
```
network:
    version: 2
    renderer: networkd
    ethernets:
      ens18:
        dhcp4: no
        addresses: [x.x.x.x/24]
        routes:
          - to: default
            via: x.x.x.x
        nameservers:
          addresses: [x.x.x.x,x.x.x.x]
          search: []
```
