### DISCUSSION TITLE
AdGuard Home LXC Container not working in sidebar of Home Assistant via “panel_iframe”

### DISCUSSION THREAD

**Discussion by carsten-h** [tteck/Proxmox#2700] [Help Needed] [answered]
Hi!

First: Thank you very much for the great Scripts for Proxmox Containers/VMs!

Until now I used the Adguard Home Add-On in Home Assistant which integrates itself into the sidebar. This was working.

But I wanted to have Adguard Home running independently from Home Assistant as it has nothing really to do with Home Assistant.
So I set up a LXC-Container on my Proxmox Server with Adguard Home.
This can be reached without any problem in a browser via “http://192.168.178.104/”.

Now I tried to integrate this website into the sidebar:

```
panel_iframe:
  adguard:
    title: AdGuard Home
    icon: mdi:lightbulb-on
    url: http://192.168.178.104

```
What is happening is the following. I can see the login-page of Adguard Home like I can see it with the Adguard Home Add-On.
But then I input the correct loginname and password like directly inside the browser and the login-screen is cleared and showing again. It is not possible to go “inside” the configuration.

It is regardless where I call the Home Assistant website, I can use a browser, the iOS/iPadOS/macOS App or an Android App. I can not login.

What I see the following in the file “/var/log/AdGuardHome.err” inside the LXC-container:

`2024/03/26 16:02:45.437928 [info] auth: user "carsten" successfully logged in from ip 192.168.178.191
`
The IP-address is from my Mac where I am using the Home Assistant website.

To test if this is a general Problem I set up another LXC-Container with “Nginx Proxy Manager” and used the following configuration:

```
panel_iframe:
  nginx:
    title: Nginx
    icon: mdi:lightbulb-on
    url: http://192.168.178.105:81

```
I get the login-page of Nginx Proxy Manager and the login is possible without any problem. I can configure Nginx Proxy manager there.

So what can be the problem with Adguard Home?
Can anyone help me here?
