### DISCUSSION TITLE
zigbee2mqtt with Sonoff E dongle?

### DISCUSSION THREAD

**Discussion by copykatze** [tteck/Proxmox#2701] [Help Needed]
Hi, I have my homeassistant system working great on proxmox thanks to the [helper scrips](https://tteck.github.io/Proxmox/), so far with a sonoff dongle P and the zigbee2mqtt container.

Now I wanted to try out matter over thread, got a sonoff dongle E and tried to set it up the same way, but starting gives me this error:

```
# cd /opt/zigbee2mqtt && npm start

> zigbee2mqtt@1.36.0 start
> node index.js

Zigbee2MQTT:info  2024-03-27 13:42:04: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-03-27.13-42-04' filename: log.txt
Zigbee2MQTT:info  2024-03-27 13:42:04: Starting Zigbee2MQTT version 1.36.0 (commit #9c505fd)
Zigbee2MQTT:info  2024-03-27 13:42:04: Starting zigbee-herdsman (0.35.1)
Zigbee2MQTT:error 2024-03-27 13:42:44: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-03-27 13:42:44: Failed to start zigbee
Zigbee2MQTT:error 2024-03-27 13:42:44: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-03-27 13:42:44: Exiting...
Zigbee2MQTT:error 2024-03-27 13:42:44: Error: Failure to connect
    at Ezsp.connect (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:373:19)
    at Driver.startup (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:163:13)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:62:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:109:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
```

This is my config ([removed] some sensible data):

```
# cat /opt/zigbee2mqtt/data/configuration.yaml
frontend:
  port: 8099
  auth_token: [removed]
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqttV2
  server: mqtt://192.168.178.134
  user: [removed]
  password: [removed]
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231219140818-if00
  adapter: ezsp
advanced:
  pan_id: GENERATE
  network_key: GENERATE
  channel: 20
```

I also tried without the line "adapter: ezsp", but there were other errors ("Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'") so that seemed not to be helpful.

If someone with more experience can see some obvious mistakes and point me in the right direction, I would appreciate it very much :)
