### DISCUSSION TITLE
Passthrough USB to Zigbee2MQTT LXC

### DISCUSSION THREAD

**Discussion by maxshcherbina** [tteck/Proxmox#2777] [Help Needed]
I am trying to add my Conbee II to the Zigbee2MQTT LXC and I am not sure how to do it correctly.

Error I get from starting Z2MQTT:

```
Zigbee2MQTT:debug 2024-04-11 13:57:44: Loaded state from file /opt/zigbee2mqtt/data/state.json
Zigbee2MQTT:info  2024-04-11 13:57:44: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-04-11.13-57-44' filename: log.txt
Zigbee2MQTT:debug 2024-04-11 13:57:44: Removing old log directory '/opt/zigbee2mqtt/data/log/2024-04-11.13-55-42'
Zigbee2MQTT:info  2024-04-11 13:57:44: Starting Zigbee2MQTT version 1.36.1 (commit #ffc2ff1d)
Zigbee2MQTT:info  2024-04-11 13:57:44: Starting zigbee-herdsman (0.40.3)
Zigbee2MQTT:debug 2024-04-11 13:57:44: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":24497},"serialPort":{"adapter":"deconz","path":"/dev/ttyACM0"}}'
Zigbee2MQTT:error 2024-04-11 13:57:55: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-04-11 13:57:55: Failed to start zigbee
Zigbee2MQTT:error 2024-04-11 13:57:55: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-04-11 13:57:55: Exiting...
Zigbee2MQTT:error 2024-04-11 13:57:55: undefined
```

My lxc 102.conf:
```

## Zigbee2MQTT LXC
#  ### http%3A//192.168.1.202%3A8080
#
#To create a new Proxmox VE Zigbee2MQTT LXC, run the command below in the Proxmox VE Shell.
#To Update Zigbee2MQTT, run the command below (or type update) in the LXC Console.
#
#bash -c "$(wget -qLO - https%3A//github.com/tteck/Proxmox/raw/main/ct/zigbee2mqtt.sh)"
arch: amd64
cores: 2
features: keyctl=1,nesting=1
hostname: zigbee2mqtt
memory: 1024
net0: name=eth0,bridge=vmbr0,hwaddr=8E:BD:DC:B8:C5:86,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-102-disk-0,size=4G
swap: 512
tags: home-automation;zigbee
unprivileged: 1
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2132478-if00 /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2132478-if00  non>
lxc.cgroup2.devices.allow: c 166:* rwm
lxc.mount.entry: /dev/ttyACM0 dev/ttyACM0  none bind,optional,create=file
```

and my rules:
```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1cf1", ATTRS{idProduct}=="0030", GROUP="users", MODE="0666"
```

If someone can provide some insight, Id be greatly appreciative.

**Comment by tteck** [comment]
When a Zigbee2MQTT LXC is created privileged it already has USB passthrough configured. You then edit the `/opt/zigbee2mqtt/data/configuration.yaml` to define the location of your Conbee II. 

I have no idea why you're doing that crazy stuff 🤷🏻‍♂️ 

Read the instructions below the LXC creation command. There's even an example `configuration.yaml`

**Comment by tteck** [comment]
> unprivileged: 1

This is an issue

**Comment by maxshcherbina** [comment]
Thanks a lot! 

I have now re-installed z2MQTT (which actually meant I had to first install proxmox 8.1.1) 

Now I have installed the debian z2mqtt with all the default settings, so it is now privileged. 

However, I am still getting errors when trying to start it.

```
debug 2024-04-11 18:31:25: Loaded state from file /opt/zigbee2mqtt/data/state.json
info  2024-04-11 18:31:25: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-04-11.18-31-25' filename: log.txt
debug 2024-04-11 18:31:25: Removing old log directory '/opt/zigbee2mqtt/data/log/2024-04-11.18-29-28'
info  2024-04-11 18:31:25: Starting Zigbee2MQTT version 1.36.1 (commit #ffc2ff1)
info  2024-04-11 18:31:25: Starting zigbee-herdsman (0.40.3)
debug 2024-04-11 18:31:25: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":24497},"serialPort":{"adapter":"deconz","path":"/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2132478-if00"}}'
error 2024-04-11 18:31:36: Error while starting zigbee-herdsman
error 2024-04-11 18:31:36: Failed to start zigbee
error 2024-04-11 18:31:36: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2024-04-11 18:31:36: Exiting...
error 2024-04-11 18:31:36: undefined
```


As per your guide, I updated my config to have a path similar to yours.

```
homeassistant:
  status_topic: homeassistant/status
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.201
  user: mqttuser
  password: ####
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  adapter: deconz
  # port: /dev/ttyACM0
  port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2132478-if00
frontend:
  port: 8080
advanced:
  pan_id: 24497
  ext_pan_id:
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
  channel: 11
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  last_seen: ISO_8601_local
  log_level: debug
```

I also confirmed that the usb is being passed to the LXC:
```
root@zigbee2mqtt:~# ls -l /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2132478-if00
lrwxrwxrwx 1 root root 13 Apr 11 18:19 /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2132478-if00 -> ../../ttyACM0
```

using `port: dev/ttyACM0` produces a very similar error, unfortunately.

I will try without my database next

**Reply by tteck** [reply]
Where is `adapter: deconz	#(uncomment for ConBee II)`? 
Study the example `configuration.yaml`

**Reply by maxshcherbina** [reply]
```
serial:
  adapter: deconz
  # port: /dev/ttyACM0
  port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2132478-if00
```

I have that in the code above?
