### DISCUSSION TITLE
Homepage LXC - issue with utils.

### DISCUSSION THREAD

**Discussion by TeaJhay** [tteck/Proxmox#2834] [Help Needed]
Not at all sure it's an issue with the script or the build but Homepage LXC has issues with atleast one of it's info widgets. Particularly open-meteo. Can ping api.open-meteo.com however curl gives back an error and the standard config for the widget gives API error (500 internal server)

tried update (which I had fail on another homepage LXC vm) but didn't resolve.

tried standard docker install for homepage on windows, linux mint and an alpine-docker LXC with docker compose. all worked. Not sure what's the issue with the homepage LXC directly but it's something the update doesn't find and I'm not entirely sure to look for. (started thinking I had to disect my proxmox install to see why nslookup and ping worked but the actuall call didn't). Could it be an issue with the source install of homepage? should I log an issue over there?

**Comment by TeaJhay** [comment]
Adding onto this, I tried a source install on an ubuntu lxc and failed. Issues with Storage.js. Will try again on a Debian lxc to match the homepage script's environment

**Reply by TeaJhay** [reply]
Created a debian LXC and build Homepage from source with npm. Works as expected. Something seems to be going on in the script, perhaps configuration?

Edit: tried homepage install with Bookworm and Bullseye, neither work. Not sure where to go further to diagnose? chat GPT seems to think it's an issue perhaps surrounding react but I don't know.

**Reply by tteck** [reply]
How does yours differ from
https://github.com/tteck/Proxmox/blob/c073351b4c9bd91c1fbb7f7172c3b9a79d47de61/install/homepage-install.sh#L39-L50

**Reply by TeaJhay** [reply]
steps I took for a working container:
pre-homepage I ran your Debian LXC script, configured with the same specs as the homepage script (2vcpu, 1gb memory etc) dhcp and defaults except a custom root password then installed npm and git with "apt install"

```
cd /opt/
git clone https://github.com/gethomepage/homepage.git
cd Homepage/
npm install
npm run build
cp src/skeleton/* config/
npm start &
```
using 5x the idle memory but it works. I then just copy the standard open-meteo widget over to widget.yaml in /opt/homepage/config and it functions. not sure why it's getting an Api error when made with the Homepage LXC script, nor if just no one else has noticed or it's only affecting me.

```
- openmeteo:
    label: Kyiv # optional
    latitude: 50.449684
    longitude: 30.525026
    timezone: Europe/Kiev # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
```
If you need any logs from the install, let me know and ill paste them in.
