### DISCUSSION TITLE
[Request] Traefik as a service in a LXC Container

### DISCUSSION THREAD

**Discussion by Uzurka** [tteck/Proxmox#2996] [Ideas]
This... This request can be weird.
For years now, i use Traefik as a reverse proxy & load-balancer for all my services exposed to the WEB
Recently, for security purposes, i decided to put traefik container in an isolated virtual machine, but it requires a VM with : 
- Debian
- Docker
- Traefik
- All the stuff i deploy using Ansible to monitor, secure, and access to this VM

This is heavy

Even if it's not documented by Traefik themselves,[ traefik can be installed as a service on Debian, in a simple way tho](https://j.hommet.net/traefik-binaire-sans-docker/)
Wonder if someone could do a script here that handles that in a LXC Container :)

**Comment by Uzurka** [comment]
Scripts & merge done.
https://github.com/tteck/Proxmox/commit/07585658b0edea4dce99e7b41420164d83e488d4
This installs a very basic traefik service. 
Things to edit : 
/etc/traefik/config.yaml : 
```
certificatesResolvers:
  letsencrypt:
    acme:
      email: "foo@bar.com"
      storage: /etc/traefik/ssl/acme.json
      tlsChallenge: {}
```

Replace your email address here

For those who wants to use OVH/Cloudflare/Other registrar DNS challenge for TLS : 
Add to /etc/systemd/system/traefik.service the variables like : 
```
[Unit]
Description=Traefik

[Service]
Type=notify
ExecStart=/usr/bin/traefik --configFile=/etc/traefik/traefik.yaml
Restart=on-failure
ExecReload=/bin/kill -USR1 $MAINPID
Environment="CF_API_EMAIL=REDACTED"
Environment="CF_API_KEY=REDACTED"
Environment="OVH_ENDPOINT=REDACTED"
Environment="OVH_APPLICATION_KEY=REDACTED"
Environment="OVH_APPLICATION_SECRET=REDACTED"
Environment="OVH_CONSUMER_KEY=REDACTED"

[Install]
WantedBy=multi-user.target
```

This line in the service : 
`ExecReload=/bin/kill -USR1 $MAINPID`
Permit logrotate postrotate (Traefik will close and reopen the logs files when receive USR1 kill signal)

By default, access logs will be in JSON format, which is parseable by Crowdsec-bouncer using the crowdsecurity/traefik-logs parser

Here's an exemple of a router configuration (stored in /etc/traefik/conf.d/router_name.yml) : 

```
http:
  routers:
    gitea:
      entryPoints:
        - "websecure"
      rule: "Host(`git.foo.bar`)"
      tls:
        certresolver: letsencrypt
      service: gitea

  services:
    gitea:
      loadBalancer:
        servers:
          - url: "http://192.168.1.11:8186"
        passHostHeader: true

```

conf.d folder contains dynamic configuration, which means that Traefik don't need a restart nor a reload to use those files.
For more examples, like middlewares, refer to traefik documentation, make sure to select "yaml" instead of docker labels. 
toml also works

**Comment by di5cord20** [comment]
Just finished setting up my Traefik LXC - worked perfectly!  Thanks for the great script.

**Reply by info-path** [reply]
Can variables be defined in another way? For example in an .env file? I'm trying to define the variable TRAEFIK_DASHBOARD_CREDENTIALS in file `/etc/systemd/system/traefik.service:`
```
[Service]
Environment="TRAEFIK_DASHBOARD_CREDENTIALS=admin:$$2v$$05$$T.7NADpWqYcsVtiq0pSbXeXABxprzol9/eZ7iM08nnVVYNXVroGAa"
```

but I keep getting an error with this entry:
```
middlewares:
traefik-auth:
  basicAuth:
    users: 
      - "${TRAEFIK_DASHBOARD_CREDENTIALS}"
```

Error:
```
{"level":"error","entryPointName":"https","routerName":"traefik-secure@file","error":"error parsing BasicUser: ${TRAEFIK_DASHBOARD_CREDENTIALS}","time":"2024-06-25T00:01:17+02:00"}
```
