### DISCUSSION TITLE
Frigate LXC - Update Frigate

### DISCUSSION THREAD

**Discussion by TiDO2k** [tteck/Proxmox#3252] [Q&A]
Hello,
thank for the Frigate LXC  setup script.

How can I update frigate? 
The "update" command in the shell doesn't work.

Best regards
TiDO

**Comment by ChienDeLaCasse** [comment]
Hello to all,
I also want to thank Tteck and contributors for all those helpful scripts.
I concur with @TiDO2k and have exactly the same question, i currently have Frigate 0.13.2 in a Proxmox container thanks to VE scripts.

Is there a way to make an update or do I have to "wipe" the container ?

Sorry if my questions are not clear, I am a beginner in Linux, VM and containers.

**Comment by tankknat** [comment]
an update to possibly the beta 0.14 would be great or possible versions that are avaliable.

**Comment by andy778** [comment]
It seems also to be running debian 11, an update to 12 would perhaps also be good 
https://wiki.debian.org/LTS

**Reply by tteck** [reply]
Debian 11 is required for now.
https://github.com/blakeblackshear/frigate/blob/843d301950b3779c946df0fc87b10984e4210b2c/docker/main/Dockerfile#L6

**Comment by Nindohana** [comment]
Hello, anyone found a way to update the frigate LXC ?

**Reply by tteck** [reply]
Update to what?

**Reply by Nindohana** [reply]
How do we update the frigate LXC to future version?
or in this case to the 0.14 beta?

**Comment by wildchai** [comment]
hope to have this answer as well. Need to know how to update to latest version. 

Thanks

**Comment by Vendo233** [comment]
I`m having issue with Frigate LXC where Frigat stops working and Memory and Swap are 100%. ( memory leak? ) 
What can I do? 
After reboot the LXC works and then in several hours when memory and swap is maxxed out it hangs

**Reply by Chrischi-** [reply]
Are you using opus in your go2rtc configuration?
This is a known bug that has been fixed in Frigate 14.x.

I simply deactivated audio in my go2rtc configuration. Since then, the memory leak has stopped occurring.

@tteck 
But I am also interested in how we could update to the 14.x beta.

**Comment by mikecitt** [comment]
Anyone managed to update do 0.14.0?
We have RC: https://github.com/blakeblackshear/frigate/discussions/12645

**Reply by TiDO2k** [reply]
I think there is nobody who can help us.
So the only solution will be to use docker compose to install the latest version of frigate

**Comment by xekil** [comment]
Good morning,

[Frigate v 0.14 is available in stable version](https://github.com/blakeblackshear/frigate/releases/tag/v0.14.0), how to update because the script does not work?

THANKS

` bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/frigate.sh)"`

```
    ______     _             __
   / ____/____(_)___ _____ _/ /____
  / /_  / ___/ / __ `/ __ `/ __/ _ \
 / __/ / /  / / /_/ / /_/ / /_/  __/
/_/   /_/  /_/\__, /\__,_/\__/\___/
             /____/

Loading...
 ✗ There is currently no update path available.

```

**Reply by xekil** [reply]
Hello,  I have just created a new container LXC to upgrade to version 0.14 and I have been trying to start frigate for more than 3 hours which refuses to launch, I thought it was coming from my configuration file which was not compatible with the new version...

A new script is needed according to [this post](https://github.com/tteck/Proxmox/discussions/2711#discussioncomment-10278460_)

Here are my daemon.log logs

```
Aug  8 23:33:29 frigate systemd[1]: Starting Nginx service...
Aug  8 23:33:29 frigate systemd[1]: Started Nginx service.
Aug  8 23:33:29 frigate systemd[1]: nginx.service: Main process exited, code=exited, status=127/n/a
Aug  8 23:33:29 frigate systemd[1]: nginx.service: Failed with result 'exit-code'.
```

THANKS

**Comment by gianlucaf81** [comment]
We confidently await another tteck miracle

**Reply by xekil** [reply]
There was a new pr and the script now correctly installs frigate 0.14, I just tested :)

https://github.com/tteck/Proxmox/discussions/2711#discussioncomment-10282240_

**Reply by stinobook** [reply]
can confirm, clean install works. no updating yet though.

**Reply by xekil** [reply]
false joy, go2rtc does not want to launch, my cameras do not display

```
12:34:01,166 | info | go2rtc version=1.9.4 platform=linux/amd64 revision=a4885c2
12:34:01,166 | info | config path=/dev/shm/go2rtc.yaml
12:34:01,166 | info | [rtsp] listen addr=:8554
12:34:01,166 | info | [webrtc] listen addr=:8555/tcp
12:34:01,170 | info | [api] listen addr=:1984
12:45:16,195 | warn | undefined error=unsupported method: GET caller=github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:230
12:45:17,257 | warn | undefined error=unsupported method: GET caller=github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:230
12:45:22,286 | warn | undefined error=unsupported method: GET caller=github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:230

```

**Reply by stinobook** [reply]
works fine here. 
![image](https://github.com/user-attachments/assets/0a617d17-7f0e-4993-aeae-073ef56085d7)

**Reply by xekil** [reply]
Maybe my configuration is no longer correct, I use this, any idea? THANKS
```
go2rtc:
  webrtc:
    candidates:
    - 192.168.1.210:8555          # IP LXC
    - stun:8555                  
    
  streams:
    gate_hd:
      - rtsp://user:mp@192.168.1.200:554/Streaming/Channels/101
    gate_sd:
      - rtsp://user:mp@192.168.1.200:554/Streaming/Channels/102
      
cameras:
  gate:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy 
      inputs:
      - path: rtsp://127.0.0.1:8554/gate_hd    
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/gate_sd  
        input_args: preset-rtsp-restream
        roles:
        - detect
```

**Reply by stinobook** [reply]
> - 192.168.1.210:8555          # IP LXC

i figure you made a NEW container to try frigate 14, so is that IP still the correct one ?
just use localhost:8555, that works fine.

**Reply by xekil** [reply]
yes I created a new container, the IP was modified accordingly, I'm going to remove this line and do a test after restoring my backup of the container because I tested a lot of stuff that wasn't very clean :)

**Reply by stinobook** [reply]
what does http://192.168.1.210:1984 give you? should give the go2rtc UI.

**Reply by xekil** [reply]
yes I had the interface accessible, that's where I copied the logs

**Reply by stinobook** [reply]
so technically go2rtc works. is your frigate 13 still running? maybe your cameras have a max allowed number of streams.

**Reply by xekil** [reply]
frigate 13 is stopped, I just restored my container with virgin frigate 14, I copied my configuration without the following line (192.168.1.210:8555 # IP LXC) and I have this error in the logs.

I have the impression that frigate cannot communicate with go2rtc on port 8554

```
error 2024-08-09 14:17:19 watchdog.gate Ffmpeg process crashed unexpectedly for gate.
error 2024-08-09 14:17:19 watchdog.gate The following ffmpeg logs include the last 100 lines prior to exit.
error 2024-08-09 14:17:19 ffmpeg.gate.detect [rtsp @ 0x627e839f3dc0] method DESCRIBE failed: 404 Not Found
error 2024-08-09 14:17:19 ffmpeg.gate.detect rtsp://127.0.0.1:8554/gate_sd: Server returned 404 Not Found
error 2024-08-09 14:17:19 frigate.video home: Unable to read frames from ffmpeg process.
error 2024-08-09 14:17:19 frigate.video home: ffmpeg process is not running. exiting capture thread...
error 2024-08-09 14:17:19 ffmpeg.gate.record [rtsp @ 0x6550f3a74e80] method DESCRIBE failed: 404 Not Found
error 2024-08-09 14:17:19 ffmpeg.gate.record rtsp://127.0.0.1:8554/gate_hd: Server returned 404 Not Found
info 2024-08-09 14:17:19 watchdog.gate Terminating the existing ffmpeg process...
info 2024-08-09 14:17:19 watchdog.gate Waiting for ffmpeg to exit gracefully...
```

**Reply by xekil** [reply]
add logs go 2 rtc

```
2024-08-09 14:12:59.713494  [INFO] Preparing new go2rtc config...
2024-08-09 14:13:00.510220  [INFO] Starting go2rtc...
2024-08-09 14:13:00.612925  14:13:00.611 INF go2rtc platform=linux/amd64 revision=a4885c2 version=1.9.4
2024-08-09 14:13:00.612979  14:13:00.611 INF config path=/dev/shm/go2rtc.yaml
2024-08-09 14:13:00.613000  14:13:00.612 INF [rtsp] listen addr=:8554
2024-08-09 14:13:00.613017  14:13:00.612 INF [webrtc] listen addr=:8555/tcp
2024-08-09 14:13:00.613317  14:13:00.613 INF [api] listen addr=:1984
2024-08-09 14:27:44.829141  14:27:44.829 INF go2rtc platform=linux/amd64 revision=a4885c2 version=1.9.4
2024-08-09 14:27:44.829198  14:27:44.829 INF config path=/dev/shm/go2rtc.yaml
2024-08-09 14:27:44.829583  14:27:44.829 INF [api] listen addr=:1984
2024-08-09 14:27:44.829642  14:27:44.829 INF [rtsp] listen addr=:8554
2024-08-09 14:27:44.829779  14:27:44.829 INF [webrtc] listen addr=:8555/tcp

```

**Reply by stinobook** [reply]
can you show the config from the go2rtc ui instead of from frigate? (no need to edit it, it gets reset every frigate restart)

**Reply by xekil** [reply]
Well, I'm making a little progress, but it's far from being won.

I manage to get the feed from my camera, but very stealthily, then frigate slows down and freezes, and when playing a feed, it's extremely long and unusable, one image every 20 seconds!!

My coral is well detected as well as my GPU, the processor is only used at 2% just like the GPU. The container is not loading (CPU 8%, RAM 11%), I don't understand what's happening..

Here is the go2rtc ui configuration for a single camera (I voluntarily removed my 8 other cameras, because there is no point, the configuration is identical, they are all the same, Annke C500)

```
api:
  origin: '*'
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
streams:
  gate_hd:
  - rtsp://user:mp@192.168.1.200:554/Streaming/Channels/101
  gate_sd:
  - rtsp://user:mp@192.168.1.200:554/Streaming/Channels/102
webrtc:
  candidates:
  - stun:8555
  listen: :8555
```

I think there is a problem with go2rtc and frigate 14 lxc.

Could anyone try with a similar configuration?
(go2rtc and webrtc to stream the camera feed)

In the meantime, I'm going back to frigate 13 and will continue looking for a solution later as I have to leave for a few hours, thanks for your help.

THANKS

**Reply by xekil** [reply]
Look my Frigate 14

![image](https://github.com/user-attachments/assets/d742dce4-ac85-4a80-8382-82cea0bd11fc)

**Reply by Vendo233** [reply]
> frigate 13 is stopped, I just restored my container with virgin frigate 14, I copied my configuration without the following line (192.168.1.210:8555 # IP LXC) and I have this error in the logs.
> 
> I have the impression that frigate cannot communicate with go2rtc on port 8554
> 
> ```
> error 2024-08-09 14:17:19 watchdog.gate Ffmpeg process crashed unexpectedly for gate.
> error 2024-08-09 14:17:19 watchdog.gate The following ffmpeg logs include the last 100 lines prior to exit.
> error 2024-08-09 14:17:19 ffmpeg.gate.detect [rtsp @ 0x627e839f3dc0] method DESCRIBE failed: 404 Not Found
> error 2024-08-09 14:17:19 ffmpeg.gate.detect rtsp://127.0.0.1:8554/gate_sd: Server returned 404 Not Found
> error 2024-08-09 14:17:19 frigate.video home: Unable to read frames from ffmpeg process.
> error 2024-08-09 14:17:19 frigate.video home: ffmpeg process is not running. exiting capture thread...
> error 2024-08-09 14:17:19 ffmpeg.gate.record [rtsp @ 0x6550f3a74e80] method DESCRIBE failed: 404 Not Found
> error 2024-08-09 14:17:19 ffmpeg.gate.record rtsp://127.0.0.1:8554/gate_hd: Server returned 404 Not Found
> info 2024-08-09 14:17:19 watchdog.gate Terminating the existing ffmpeg process...
> info 2024-08-09 14:17:19 watchdog.gate Waiting for ffmpeg to exit gracefully...
> ```

I'm going through all these links and I'm unable to find the new link, can somebody help me pls

**Reply by Vendo233** [reply]
> There was a new pr and the script now correctly installs frigate 0.14, I just tested :)
> 
> [#2711 (comment)](https://github.com/tteck/Proxmox/discussions/2711#discussioncomment-10282240)_

Can somebody help me with the 14 link/script? I do not have NVIDIA card only Coral

**Reply by xekil** [reply]
there is no new link, the script currently installs the latest version which is 0.14

**Reply by Vendo233** [reply]
> there is no new link, the script currently installs the latest version which is 0.14

This one?

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/frigate.sh)"

**Reply by xekil** [reply]
Yes

**Reply by xekil** [reply]
Attention ,there is a problem with GO2RTC, there are 2 of us for the moment who have this problem, try by configuring GO2RTC, Frigate does not work...

**Reply by Vendo233** [reply]
> Yes

Thank you sir, will jump on testing momentarily

**Comment by gustjoha** [comment]
I also can´t get go2rtc to work, it does not look like Frigate config is parsing it over to the go2rtc. 

If I load my cameras without go2rtc in Frigate directly, they work.

There is nothing showing in the logs of go2rtc or Frigate to indicate the issue.

**Reply by xekil** [reply]
I feel less alone, hoping that this problem is not too complicated to correct

**Reply by gustjoha** [reply]
I am able to enter the config directly in go2rtc like this which works for me but I suppose that config will be wiped out when the lxc reboots.

```
webrtc:
  candidates:192.168.1.175 
  - stun:8555
streams:
    Front: rtsp://admin:secret@192.168.1.64/Streaming/Channels/101
    Front_sub: rtsp://admin:secret@192.168.1.64/Streaming/Channels/102
    Terrace: rtsp://admin:secret@192.168.2.52/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46ZnJpZ2F0ZTEyMzQ=
    Terrace_sub: rtsp://admin:secret@192.168.2.52/cam/realmonitor?channel=1&subtype=01&authbasic=YWRtaW46ZnJpZ2F0ZTEyMzQ
    Garage: rtsp://admin:secret@192.168.1.95/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46ZnJpZ2F0ZTEyMzQ=
    Garage_sub: rtsp://admin:secret@192.168.1.95/cam/realmonitor?channel=1&subtype=01&authbasic=YWRtaW46ZnJpZ2F0ZTEyMzQ
    Front-side: rtsp://admin:secretc@192.168.1.65/Streaming/Channels/101
    Front-side_sub: rtsp://admin:secret@192.168.1.65/Streaming/Channels/102 
```
