### DISCUSSION TITLE
How to add "client_max_body_size 0;" into Nginx Proxy Server?

### DISCUSSION THREAD

**Discussion by Stooovie** [tteck/Proxmox#3650] [Help Needed]
Hi, I'm trying to fix a "413 Request Entity Too Big" on Nextcloud AIO (I can't upload/sync a 5GB file), solutions point to a "client_max_body_size" limit set too low in NPM.

I tried creating a custom client_max_body_size.conf file with "client_max_body_size 0;" as content and mounting it in the docker.compose.yml like this (last line)
```

version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      **- ./client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf**
```

and rebooted the LXC, but it didn't help.

Any clues or tips? Thanks!
