### DISCUSSION TITLE
Frigate LXC M.2 Coral TPU Config

### DISCUSSION THREAD

**Discussion by hanley-development** [tteck/Proxmox#3666] [Help Needed] [answered]
After much perseverance i was able to get the m.2 coral tpu to be recognized by proxmox. 

Here are the steps I took for that:
```bash
#Install dependencies packages
apt-get install devscripts dh-make dh-dkms git

#Download Driver package
git clone https://github.com/feranick/gasket-driver.git

#Build Deb file
cd gasket-driver/
debuild -us -uc -tc -b

#Install with apt
cd ..
apt install ./gasket*.deb -y
modprobe gasket
```

Found out I couldn't install the driver because I had secure boot enabled
```
root@pve4:/# mokutil --sb-state
SecureBoot enabled
```

Disabled secure boot in bios

Finally I was able to install the driver and modprobe gasket
```
root@pve4:/# lsmod | grep apex
apex                   28672  0
gasket                126976  1 apex

root@pve4:/# ls -l /dev/apex*
crw-rw---- 1 root root 120, 0 Sep  5 00:05 /dev/apex_0

```

Appended the lxc .conf file with 
```
lxc.cgroup2.devices.allow: c 120:0 rwm
lxc.mount.entry: /dev/apex_0 dev/apex_0 none bind,optional,create=file
```

My complete step-up now has the 
```
#<div align='center'><a href='https%3A//Helper-Scripts.com' target='_blank' rel='noopener noreferrer'><img src='https%3A//raw.githubusercontent.com/tteck/Proxmox/main/misc/images/logo-81x112.png'/></a>
#
#  # Frigate LXC
#
#  <a href='https%3A//ko-fi.com/proxmoxhelperscripts'><img src='https%3A//img.shields.io/badge/&#x2615;-Buy me a coffee-blue' /></a>
#  </div>
arch: amd64
cores: 4
features: nesting=1
hostname: frigate
memory: 1024
net0: name=eth0,bridge=vmbr0,hwaddr=BC:24:11:34:60:6D,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: vmstorage_nfs:100/vm-100-disk-0.raw,size=20G
swap: 512
tags: proxmox-helper-scripts
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyUSB1       dev/ttyUSB1       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM1       dev/ttyACM1       none bind,optional,create=file
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
lxc.cgroup2.devices.allow: c 120:0 rwm
lxc.mount.entry: /dev/apex_0 dev/apex_0 none bind,optional,create=file

```

The LXC sees that it has the Coral TPU
```
root@frigate:~# lspci | grep Coral
03:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
```

The only problem now is adding the TPU to the Frigate config.

```yaml
root@frigate:~# cat /config/config.yml
mqtt:
  enabled: false
cameras:
  test:
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
        - path: /media/frigate/person-bicycle-car-detection.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    detect:
      height: 1080
      width: 1920
      fps: 5
detectors:
  ov:
    type: openvino
    device: CPU
    model:
      path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
  coral1:
    type: edgetpu
    device: pci:0
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

Restarted Frigate.... but doesnt detect the TPU
Is there something I am missing for the application to see the tpu?

**Comment by jhmeier** [comment]
did you test
  coral1:
    type: edgetpu
    device: pci

That's what I am using in my docker frigate.

**Reply by hanley-development** [reply]
The docker environment I was using does work. When using: https://tteck.github.io/Proxmox/#frigate-lxc there seems to be an issue with getting the system to recognize the card is available.

**Comment by MichaelPankow** [comment]
Could be a permission issue of the device file. What is the output of  "ls -l /dev/apex*" in the container?
You can also try to passthrough apex device using the GUI in lxc->Resources->Add->Device Passthrough and add
/dev/apex_0, gid=1000
You should also try to add apex group in host "groupadd apex".
Also you can create a new node with correct permission and passthrough that device
```
root@pmox00:/# cd /lxc/102010/devices

root@pmox00:/lxc/102010/devices:/# mknod -m 660 apex_0 c 120 0

root@pmox00:/lxc/102010/devices/# chown 100000:100020 apex_0

root@pmox00:/lxc/102010/devices# ls -la apex_0
crw-rw---- 1 100000 100020 120, 0 Sep  6 22:01 apex_0
```
in lxc.conf
```
lxc.cgroup2.devices.allow: c 120:* rwm
lxc.mount.entry: /lxc/102010/devices/apex_0 dev/apex_0 none bind,optional,create=file 0,0
```

**Reply by hanley-development** [reply]
```
root@frigate:/config# ls -l /dev/apex*
crw-rw---- 1 root root 120, 0 Sep  5 00:05 /dev/apex_0
```

**Reply by hanley-development** [reply]
```
root@frigate:~# ls -l /dev/apex*
crw-rw---- 1 root 1000 120, 0 Sep  6 23:52 /dev/apex_0
```
also tried through the gui. whats odd is I don't see anything in the logs indicating it is trying to use the TPU.

**Reply by MichaelPankow** [reply]
The group ID is now correct. What does the log and frigate system metrics show (log can also be found in /dev/shm/logs/frigate)?

**Comment by hanley-development** [comment, marked as answer]
Banged my head on the wall for an hour. Finally realized that you can't both the openvino and edgetpu in the same config. Working now!

```
root@frigate:~# cat /config/config.yml
mqtt:
  enabled: false
cameras:
  test:
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
        - path: /media/frigate/person-bicycle-car-detection.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    detect:
      height: 1080
      width: 1920
      fps: 5
detectors:
  coral1:
    type: edgetpu
    device: pci:0
```
