### DISCUSSION TITLE
XDG_RUNTIME_DIR lxc frigate debian proxmox

### DISCUSSION THREAD

**Discussion by Damianeex** [tteck/Proxmox#3789] [Q&A]
Hi,
I've been using Frigate from the TTECK script for a few days, and I have two cameras (H.264 and H.265). Unfortunately, the CPU usage is at 90%. I have a Dell Wyse 5070 with a J5005 processor (Gemini Lake) and Intel UHD Graphics 605 GPU. 
Proxmox 8.2.7
kernel  6.8.12-1-pve 

However, LXC does not detect the GPU. When I run the vainfo command, I receive an error message:

```
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
error: failed to initialize display
```
In the /etc/systemd/system/frigate.service file, I added:

```
[Service]
#Environment="LIBVA_DRIVER_NAME: i965"
export XAUTHORITY=/var/run/lightdm/root/:0
export DISPLAY=:0
```

but doesn't work

In the /etc/pve/lxc/105.conf file from proxmox , priviligiet container
```
#  # Frigate LXC
#
#  <a href='https%3A//ko-fi.com/proxmoxhelperscripts'><img src='https%3A//img.shields.io/badge/&#x2615;-Buy me a coffee-blue' /></a>
#  </div>
arch: amd64
cores: 4
features: nesting=1
hostname: frigate
memory: 4096
net0: name=eth0,bridge=vmbr0,gw=192.168.1.1,hwaddr=BC:24:11:4C:D2:4E,ip=192.168.1.165/24,type=veth
onboot: 1
ostype: debian
rootfs: dysk500gb:vm-105-disk-0,size=125G
swap: 512
tags: proxmox-helper-scripts
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyUSB1       dev/ttyUSB1       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM1       dev/ttyACM1       none bind,optional,create=file
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
```
,

frigate conf.yaml:

```
mqtt:
  host: ---
  port: 1883
  user: ---
  password: ----
  topic_prefix: frigate


ffmpeg:
  hwaccel_args: preset-rpi-64-h265
#  hwaccel_args: preset-vaapi




cameras:
  tyl:
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h265
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://admin:pass@192.168.1.170:554/H264/ch1/main/av_stream # <----- Update for your camera
          roles:
            - detect
            - record
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
    detect:
      height:
      width:
      fps: 5


  Front: # <------ Name the camera
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h265
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://admin:pass@192.168.1.171:554/stream0#backchannel=1  # 
          roles:
            - detect
            - record
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 2
        mode: motion




    motion:
      mask: 
        0.074,0.958,0.277,0.261,0.387,0.188,0.445,0.143,0.511,0.132,0.593,0.118,0.634,0.164,0.706,0.244,0.757,0.321,0.832,0.348,0.988,0.861,0.76,0.958,0.411,0.972
model:
  path: /cpu_model.tflite




#environment_vars:
#  LIBVA_DRIVER_NAME_JELLYFIN: i965
#  LIBVA_DRIVER_NAME: i965
version: 0.14

```

lspci in the lxc:

```
00:00.0 Host bridge: Intel Corporation Gemini Lake Host Bridge (rev 03)
00:00.3 System peripheral: Intel Corporation Celeron/Pentium Silver Processor Gaussian Mixture Model (rev 03)
00:02.0 VGA compatible controller: Intel Corporation GeminiLake [UHD Graphics 605] (rev 03)
00:0e.0 Audio device: Intel Corporation Celeron/Pentium Silver Processor High Definition Audio (rev 03)
00:0f.0 Communication controller: Intel Corporation Celeron/Pentium Silver Processor Trusted Execution Engine Interface (rev 03)
00:12.0 SATA controller: Intel Corporation Celeron/Pentium Silver Processor SATA Controller (rev 03)
00:14.0 PCI bridge: Intel Corporation Gemini Lake PCI Express Root Port (rev f3)
00:14.1 PCI bridge: Intel Corporation Gemini Lake PCI Express Root Port (rev f3)
00:15.0 USB controller: Intel Corporation Celeron/Pentium Silver Processor USB 3.0 xHCI Controller (rev 03)
00:17.0 Signal processing controller: Intel Corporation Device 31b4 (rev 03)
00:17.3 Signal processing controller: Intel Corporation Device 31ba (rev 03)
00:1c.0 SD Host controller: Intel Corporation Celeron/Pentium Silver Processor SDA Standard Compliant SD Host Controller (rev 03)
00:1f.0 ISA bridge: Intel Corporation Celeron/Pentium Silver Processor LPC Controller (rev 03)
00:1f.1 SMBus: Intel Corporation Celeron/Pentium Silver Processor Gaussian Mixture Model (rev 03)
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
02:00.0 SATA controller: JMicron Technology Corp. JMB58x AHCI SATA controller

```

 lspci -nnk
```
00:00.0 Host bridge [0600]: Intel Corporation Gemini Lake Host Bridge [8086:31f0] (rev 03)
lspci: Unable to load libkmod resources: error -2
00:00.3 System peripheral [0880]: Intel Corporation Celeron/Pentium Silver Processor Gaussian Mixture Model [8086:3190] (rev 03)
        Subsystem: Dell Celeron/Pentium Silver Processor Gaussian Mixture Model [1028:080c]
00:02.0 VGA compatible controller [0300]: Intel Corporation GeminiLake [UHD Graphics 605] [8086:3184] (rev 03)
        Subsystem: Dell UHD Graphics 605 [1028:080c]
        Kernel driver in use: vfio-pci
```
