### DISCUSSION TITLE
Wireguard, Transmission & Prowlarr

### DISCUSSION THREAD

**Discussion by adub86** [tteck/Proxmox#3861] [Q&A] [answered]
Relatively new to this. 

Been tinkering for a few hours but can't seem to have the following function properly.

Have all three of these in LXC containers via the scripts.

Can anyone point me to a guide or resource that would help as follows:

1. Transmission container connects externally only through WireGuard but have all other containers still have access locally to it; 
2. Prowlarr do the same as Transmission;
3. Have the WireGuard container default to only use the VPN that has already been set up via the WebGUI.

In all instances if WireGuard is not connected to its main VPN config then no traffic flows out of Transmission or Prowlarr containers externally.

Any help would be greatly appreciated!

**Comment by Porencephaly** [comment, marked as answer]
You can accomplish this easier by running gluetun, transmission, and prowlarr together in a docker compose file and having transmission & prowlarr depend on gluetun's network. Here's a video tutorial: https://www.youtube.com/watch?v=9dJPOd0XbN8


Example docker compose file:
```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # Hostname to use for container, required in some instances for the rest of the stack to each other endpoints 
    hostname: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 9117:9117 # Jackett
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
    volumes:
      - /home/ubuntu/docker/arr-stack/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=<YOUR_PRIVATE_KEY> # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      - WIREGUARD_ADDRESSES=10.5.0.2/32
      # Timezone for accurate log times
      - TZ=Europe/London
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8085
    volumes:
      - /home/ubuntu/docker/arr-stack/qbittorrent:/config
      - /home/ubuntu/docker/arr-stack/qbittorrent/downloads:/downloads
    depends_on:
      - gluetun
    restart: always
```
