### DISCUSSION TITLE
Issues with Zigbee2MQTT LXC Container: "z2m: Error while starting zigbee-herdsman"

### DISCUSSION THREAD

**Discussion by SimsJM** [tteck/Proxmox#3927] [Help Needed] [answered]
Hi there!

I'm hoping someone smarter than me can help. I've tried to set up Zigbee2MQTT using a script from here: https://tteck.github.io/Proxmox/#zigbee2mqtt-lxc. My zigbee dongle is the [SONOFF Universal Zigbee 3.0 USB Dongle Plus Gateway with Antenna](https://www.amazon.co.uk/dp/B09KXTCMSC?ref=ppx_yo2ov_dt_b_fed_asin_title).

I'm getting a Zigbee herdsman error when I try to start the container.:
![Screenshot 2024-10-18 195503](https://github.com/user-attachments/assets/181bb3d7-bc90-439e-9ff7-3503741a830f)

I can see the Dongle in my proxmox shell when I run 'ls -l /dev/serial/by-id':

![Screenshot 2024-10-18 195602](https://github.com/user-attachments/assets/ed05ce0e-35b8-48f1-b94d-b188692974fd)

I can see it here: "lrwxrwxrwx 1 root root 13 Oct 18 18:01 usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e6df6787620cee118eb031d6f49e3369-if00-port0 -> ../../ttyUSB0"

My config file looks like this (username and password hidden):
[
![Screenshot 2024-10-18 195828](https://github.com/user-attachments/assets/bdf9dc2f-326b-481c-8c49-d7ce7272af7f)
](url)

I've tried some of the troubleshooting [here](https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html). Specifically, I've verified that the user I run Zigbee2MQTT as has write access to the port:

![Screenshot 2024-10-18 200109](https://github.com/user-attachments/assets/a9a8d269-ed2b-423c-8405-4962ad5a11fe)

I've also tried updating the firmware but I wasn't able to.

Can anyone help?

**Comment by tteck** [comment]
try
```
port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e6df6787620cee118eb031d6f49e3369-if00-port0
```

**Reply by tteck** [reply]
also
```
frontend:
  port: 9442
```

**Reply by tteck** [reply]
https://github.com/tteck/Proxmox/discussions/2917

**Comment by tteck** [comment]
Looking at your link, yours has the TI CC2652P + CP2102N so, you need to remove
```
adapter: ember
```

**Comment by tteck** [comment, marked as answer]
This config should work for you

```
frontend:
  port: 9442
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.0.116:1883'
  user: usr
  password: pwd
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e6df6787620cee118eb031d6f49e3369-if00-port0
advanced:
  pan_id: GENERATE
  network_key: GENERATE
  channel: 20
```
