### DISCUSSION TITLE
Paperless-NGX with Tika and Gotenberg

### DISCUSSION THREAD

**Discussion by newmy-de** [tteck/Proxmox#787] [Ideas]
Paperless can make use of [Tika](https://tika.apache.org/) and [Gotenberg](https://gotenberg.dev/) for parsing and converting “Office” documents (such as “.doc”, “.xlsx” and “.odt”). If you wish to use this, you must provide a Tika server and a Gotenberg server.

This will be very useful for using Paperless-NGX ...

**Comment by dimatx** [comment]
Would be great to see this built-in... In the meantime, I was able to deploy both pretty easily with docker compose, and then simply had to point the Paperless config to the URLs for gotenberg and tika respectively.

```
version: '3'
services:
  gotenberg:
    image: thecodingmachine/gotenberg:7
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
    ports:
      - 3000:3000
  tika:
    image: apache/tika:latest
    restart: unless-stopped
    ports:
      - 9998:9998
```
