### DISCUSSION TITLE
Automate bind mount config before running LXC containers

### DISCUSSION THREAD

**Discussion by sandreas** [tteck/Proxmox#792] [Help Needed]
When I try to use a script that I plan to use a bind mount for integrating external data and adding some lxc user mappings, sometimes it is not possible to configure this before I start the container.

Example:
On [navidrome-v4.sh](https://github.com/tteck/Proxmox/blob/main/ct/navidrome-v4.sh) I would like to have 2 bind mounts in my `/etc/pve/lxc/100.conf`:

```yml
mp0: /rpool/data/shared/audio/music,mp=/music
mp1: /rpool/data/shared/config/navidrome,mp=/var/lib/navidrome
lxc.idmap: u 0 100000 1000
lxc.idmap: g 0 100000 1000
lxc.idmap: u 1000 1000 1
lxc.idmap: g 1000 1000 1
lxc.idmap: u 1001 101001 64435
lxc.idmap: g 1001 101001 64435
```

The reason for this is, that I would like to backup my navidrome config without backing up the whole container, but only the navidrome database. Unfortunately it is not possible to select these mount points in the script... 

The steps I have to take are the following (if SSH is not configured for the container):

1. install the script from tteck (container automatically starts)
2. login into container console and copy `/var/lib/navidrome/` to another directory (e.g. `/root/navidrome/`)
3. stop container and restart with my desired mount points
4. login into container console and copy  `/root/navidrome/` back to `/var/lib/navidrome/` (onto the host system via mount point)

Same problem applies to other containers that use data directories that may be shared over multiple containers (e.g. Photoprism, etc.). Is there a way to configure these kind of mount points / lxc mappings before the container starts the first time to avoid the manual steps I had to perform?

**Comment by tteck** [comment]
~Post the full contents of  `/etc/pve/lxc/100.conf`~

Never mind, I get what you're saying. You would like an option to NOT start the container until you're ready. Correct?

**Reply by sandreas** [reply]
> Never mind, I get what you're saying. You would like an option to NOT start the container until you're ready. Correct?

Well, that is part of the problem... With that option I could NOT start the container, configure the bind mounts manually and then start the container for the first time generating some files that are only created on first start (in navidrome this would be the database, main config and cache). That probably solves my main problem.

However, if you compare this LXC installation to docker setups, docker usually contains a set of environment variables to set the required config options (e.g. `ND_CONFIGFILE`, `ND_DATAFOLDER` etc.). Maybe an extended solution would be:

1. being able to set data paths within the setup routine in all scripts, that may require some data sharing (navidrome, photoprism, etc.)
2. configure the container to not start automatically

I'm not sure if this would help others, but in my use case it would be awesome to tell navidrome "Please store all your stuff here" - although this requires deep knowledge of the according app...

**Reply by tteck** [reply]
If you configure the container to not start automatically, the only thing that's configurable at that point would be `/etc/pve/lxc/xxx.conf` beings Navidrome isn't installed yet. I guess one could pause the script before `systemctl enable --now navidrome.service` to give time to modify `/var/lib/navidrome/navidrome.toml` before continuing. 

I'm thinking that's more trouble than it's worth 🤷🏻‍♂️

**Reply by sandreas** [reply]
> I'm thinking that's more trouble than it's worth 🤷🏻‍♂️

Ok... So is there something you would suggest?

**Comment by sandreas** [comment]
```yml
## Navidrome LXC
#### https%3A//tteck.github.io/Proxmox/
#<a href='https%3A//ko-fi.com/D1D7EP4GF'><img src='https%3A//img.shields.io/badge/%E2%98%95-Buy me a coffee-red' /></a>
arch: amd64
cores: 2
features: nesting=1,keyctl=1
hostname: navidrome
memory: 1024
mp0: /rpool/data/shared/audio/music,mp=/music
mp1: /rpool/data/shared/config/navidrome,mp=/var/lib/navidrome
net0: name=eth0,bridge=vmbr0,hwaddr=XXXXXXXXXXX,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: local-zfs:subvol-100-disk-0,size=4G
swap: 512
unprivileged: 1
lxc.idmap: u 0 100000 1000
lxc.idmap: g 0 100000 1000
lxc.idmap: u 1000 1000 1
lxc.idmap: g 1000 1000 1
lxc.idmap: u 1001 101001 64435
lxc.idmap: g 1001 101001 64435
```
