### DISCUSSION TITLE
conbee 2 and zigbee2mqtt

### DISCUSSION THREAD

**Discussion by titof2375** [tteck/Proxmox#843] [Help Needed]
Hello, who managed to make zigbee2mqtt work with a combee2 key, I have errors that I cannot resolve
![mqqtttt](https://user-images.githubusercontent.com/31250165/208306843-854834ab-fd0c-4a00-bf3f-1aeb5fdfaa8e.PNG)

**Comment by tteck** [comment]
Post the contents of your `/opt/zigbee2mqtt/data/configuration.yaml`

**Comment by titof2375** [comment]
![dsqdqsdqsd](https://user-images.githubusercontent.com/31250165/208307205-02697a7d-0291-49df-8064-a350780a2dea.PNG)

**Reply by tteck** [reply]
spacing is wrong with `advanced` should be inline with `serial`

```
frontend:
  port: 9442
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.86.120:1883'
  user: titof
  password: Cloe2010.
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2195985-if00-port0
  adapter: deconz		
advanced:
  pan_id: GENERATE
  network_key: GENERATE
  channel: 11
```

**Reply by titof2375** [reply]
![image](https://user-images.githubusercontent.com/31250165/208308178-ac9a6f58-2e43-4156-8a95-06d9e686e31c.png)
here is what you have with me

**Reply by tteck** [reply]
Try `/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2195985-if00-port0`

**Reply by titof2375** [reply]
![mmmm](https://user-images.githubusercontent.com/31250165/208308497-441ac103-4950-4567-9d6b-7c4b7313f46a.PNG)
it's mine alone

**Reply by tteck** [reply]
Everything's good now?

**Reply by titof2375** [reply]
![fgggggggggggggggggggggggggggggg](https://user-images.githubusercontent.com/31250165/208309372-0242533c-b6a0-4f6d-ac1a-cdd16280d4ef.PNG)
no,I always have this error

**Reply by tteck** [reply]
maybe `/dev/ttyACM0`

**Reply by titof2375** [reply]
![ccccccccccccccccccccc](https://user-images.githubusercontent.com/31250165/208310214-2c5ba0e1-75bc-477f-8ef9-1adc7bd371f8.PNG)

**Reply by tteck** [reply]
make sure it's not already running by going to IP:9442

**Reply by titof2375** [reply]
unfortunately it doesn't work either, we'll see tomorrow

**Comment by tteck** [comment]
What's the output from `ls -l /dev/serial/by-id` in the zigbee2mqtt lxc?

**Comment by titof2375** [comment]
![lkjdelkrzekjrzejroiezjr](https://user-images.githubusercontent.com/31250165/208307442-9ee90017-cdf2-4c13-bb20-ed8f4fda77c2.PNG)

**Reply by chx0003** [reply]
Replace the "serial" section in your `/opt/zigbee2mqtt/data/configuration.yaml` with:
```
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2195985-if00
  adapter: deconz
```
remember to keep the correct indentation, it should work fine with that.
