### DISCUSSION TITLE
Zigbee2mqtt ls /dev/serial/by-id doesn’t work

### DISCUSSION THREAD

**Discussion by numerobis08** [tteck/Proxmox#853] [Help Needed]
Hello I create a vm on proxmox 7.3
I'm struggling to assign the usb dongle to the vm. 
I assigned it by its id to the vm. 
On proxmox shell when I do the commande lsusb it's visible but when I try the command ls /dev/serial/by-id I have the follow " no such file or directory".

**Comment by tteck** [comment]
Did you create the Zigbee2Mqtt LXC privileged?

**Reply by numerobis08** [reply]
Hello 
I'm on a vm and not on a container.  
I tried the ls copains via the pve shell.

**Reply by tteck** [reply]
I'm confused, so no Zigbee2Mqtt LXC, so it's the addon in Home Assistant OS VM?

**Reply by numerobis08** [reply]
I created a vm with devien and installed Zigbee2mqtt ( like I did previously on my Rpi4 ). Do you have an issue an how to have proper sériel port created on the vm ?

**Reply by tteck** [reply]
I find it strange that you're asking for support from a repo that didn't provide the means that got you where you're at. Good luck!

**Reply by numerobis08** [reply]
I'm sorry i didn't explained well. as i couldn't find a solution , i move to a LXC and used your script which installed well :-). but zigbee2mqtt refuse to start. i went on the differents discussion and modify configuration.yaml changing also the port to dev/ttyUSB0 but without success. i do have a Sonoff Zigbee USB dongle. 
![image](https://user-images.githubusercontent.com/65051442/209332796-6345d698-6a0b-42d7-8d08-8eeb38273eba.png)

![image](https://user-images.githubusercontent.com/65051442/209332837-7e005584-cf84-4bf0-bfd6-d25188d17e18.png)

**Reply by tteck** [reply]
That configuration isn't from this repo. You're missing some things.
Here's the example given:
```
frontend:
  port: 9442
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.86.224:1883'
  user: usr
  password: pwd
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  #adapter: deconz		#(uncomment for ConBee II)
advanced:
  pan_id: GENERATE
  network_key: GENERATE
  channel: 20
```
