### ISSUE TITLE
Zigbee2MQTT : Error: SRSP - SYS - ping after 6000ms

### ISSUE THREAD

**Issue by ViRouF** [tteck/Proxmox#1624]
### A clear and concise description of the issue.

Following installation of zigbee2MQTT, on PVE 8.0.3 with command  `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/zigbee2mqtt.sh)`, I'm unable to start zigbee2mqtt, with following error message _Error: SRSP - SYS - ping after 6000ms_

> root@zigbee2mqtt:/opt/zigbee2mqtt# cd /opt/zigbee2mqtt && npm start
> 
> zigbee2mqtt@1.32.1 start
> node index.js
> 
> Zigbee2MQTT:info  2023-07-17 20:27:13: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-07-17.20-27-13' filename: log.txt
> Zigbee2MQTT:info  2023-07-17 20:27:13: Starting Zigbee2MQTT version 1.32.1 (commit #83205e43)
> Zigbee2MQTT:info  2023-07-17 20:27:13: Starting zigbee-herdsman (0.16.0)
> Zigbee2MQTT:error 2023-07-17 20:27:34: Error while starting zigbee-herdsman
> Zigbee2MQTT:error 2023-07-17 20:27:34: Failed to start zigbee
> Zigbee2MQTT:error 2023-07-17 20:27:34: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
> Zigbee2MQTT:error 2023-07-17 20:27:34: Exiting...
> Zigbee2MQTT:error 2023-07-17 20:27:34: **Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)**
>     at ZStackAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
>     at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
>     at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:58:27)
>     at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)
>     at start (/opt/zigbee2mqtt/index.js:107:5)

If I try to start zigbee2mqtt with USB device unplugged, then error message change to `Error: Error while opening serialport 'Error: Error: No such device or address, cannot open /dev/ttyACM0'`

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Same error message by-id or by-port. Same zigbee device and similar configuration worked in previous HA zigbee2mqtt integration (without proxmox).

`Configuration.yaml `
```
frontend:
  port: 8080
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.114:1883'
  user: mosquitto_admin
  password: *******
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  #port: /dev/ttyACM0
  port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220812084558-if00
  adapter: ezsp
advanced:
  channel: 15
```

Install parameters
<img width="618" alt="Capture d'écran 2023-07-16 182315" src="https://github.com/tteck/Proxmox/assets/105979695/442c973f-f4ec-4ab6-8966-d66ef45e99a2">
