### ISSUE TITLE
Unable to start deCONZ GUI Mode

### ISSUE THREAD

**Issue by bkarakashev** [tteck/Proxmox#2580]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am running "deconzcommunity/deconz:stabl" using docker-compose on my RasppberyPi 4 and I am able to start the deCONZ in GUI mode and access it using VNC Viwer. `sudo systemctl enable --now deconz-gui`
However when I try to do that in the Promox server after installing it using the provided deCONZ script. It is not starting the GUI mode.

This issue is probably because I am missing something rather than an issue with the installation.

This is my Docker Compose file that I am using and the GUI mode works:

```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - ./volumes/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - TZ=Europe/London
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=8080
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=<PASSWORD>
      - DECONZ_UID=1000
      - DECONZ_GID=1000
      - DECONZ_START_VERBOSE=0
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
```

Would you be able to point me in the right direction? 
I would like to be able to see the visualisation of the zigbee devices connected to my ConBee 2.

<img width="894" alt="image" src="https://github.com/tteck/Proxmox/assets/6206509/ffd83c54-ab0d-46ef-a1b0-35399f190ee6">

Thanks 

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Stop the headless service immediately.
  `sudo systemctl disable --now deconz`

Start the GUI service now and every time the system starts.
  `sudo systemctl enable --now deconz-gui`

Docs Ref:
https://phoscon.de/en/conbee2/install#linuxheadless
