### ISSUE TITLE
Zigbee2mqtt ls: cannot access '/dev/serial/by-id': No such file or directory

### ISSUE THREAD

**Issue by MRobi1** [tteck/Proxmox#30]
Trying to use your zigbee2mqtt script to setup an LXC on proxmox.

Ran steps 1 and 2 to create the LXC and allow USB passthrough.
Reboot LXC.
Installed usbutils and ran the lsusb command and I do see the USB device there.
`Bus 002 Device 071: ID 1cf1:0030 Dresden Elektronik ZigBee gateway [ConBee II]`

However when I run
`ls -l /dev/serial/by-id`

It returns
`ls: cannot access '/dev/serial/by-id': No such file or directory`

**Comment by tteck** [comment]
Can you post your `.conf` for that LXC?

**Comment by MRobi1** [comment]
Here you go

```
arch: amd64
cores: 2
features: nesting=1
hostname: zigbee2mqtt
memory: 1024
net0: name=eth0,bridge=vmbr0,hwaddr=B6:6F:9C:46:9E:21,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-110-disk-0,size=4G
swap: 512
lxc.cgroup2.devices.allow: a
lxc.cap.drop: 
lxc.autodev: 1
lxc.hook.autodev: bash -c 'for char_dev in $(find /sys/dev/char -regextype sed  -regex ".*/188:.*" -o -regex ".>
```

**Comment by tteck** [comment]
Looks correct.
What's the output of `ls -l /dev/ttyUSB0`?

**Comment by MRobi1** [comment]
Same
`ls: cannot access '/dev/ttyUSB0': No such file or directory`

**Comment by tteck** [comment]
Replace the last two lines in the `.conf` with
```yaml
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id               dev/serial/by-id         none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0                    dev/ttyUSB0             none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0                    dev/ttyACM0             none bind,optional,create=file
```
Reboot the LXC and share the output of `ls -l /dev/serial/by-id`

**Comment by MRobi1** [comment]
Getting somewhere...
```
root@zigbee2mqtt:~# ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Feb  9 20:02 usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2212845-if00 -> ../../ttyACM0
```

Zigbee2mqtt fails to start
```
Zigbee2MQTT:info  2022-02-09 20:09:30: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2022-02-09.20-09-29' filename: log.txt
Zigbee2MQTT:info  2022-02-09 20:09:30: Starting Zigbee2MQTT version 1.23.0 (commit #6ea61bae)
Zigbee2MQTT:info  2022-02-09 20:09:30: Starting zigbee-herdsman (0.14.10)
Zigbee2MQTT:error 2022-02-09 20:09:30: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-02-09 20:09:30: Failed to start zigbee
Zigbee2MQTT:error 2022-02-09 20:09:30: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-02-09 20:09:30: Exiting...
Zigbee2MQTT:error 2022-02-09 20:09:30: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.23.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.23.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-10T00_09_30_669Z-debug.log
```

In configuration.yaml I tried both port: /dev/ttyACM0 and port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2212845-if00
Same message with both.

**Comment by tteck** [comment]
ConBeeII needs 
```yaml
serial:
  port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2212845-if00
  adapter: deconz
```

**Comment by MRobi1** [comment]
Added the adapter: deconz to the configuration.yaml and same error. Cannot lock port.

**Comment by tteck** [comment]
Are you using the ConBee II with ZHA while setting up Z2M? Only 1 zigbee network per coordinator.

**Comment by MRobi1** [comment]
Nope. I've got a CC2652 on another instance of z2m running on my HASS box. 
Looking to set this up as a test network and had the Conbee laying around. Way back I used to have it connected to deconz though.

**Comment by tteck** [comment]
Just guessing here (never used a ConBee), but I'd say the firmware needs updating.

**Comment by MRobi1** [comment]
Got it :)
A little digging through the z2m issue reports and I found this gem.

"Faced the same issue. I tried to run npm start from the project folder. But got an error. This happens due to already executed zigbee2mqtt.service via systemctl."

Sure enough, navigating to http://192.168.XX.XXX:9442 and it was already running!!

Thanks for all the help with this one

**Comment by tteck** [comment]
BTW, I just ahead and added
```yaml
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
```
to the `.conf` file during the installation. Should make it a more pleasant setup process.
