### ISSUE TITLE
Frigate not detecting Coral (USB)

### ISSUE THREAD

**Issue by cjoha** [tteck/Proxmox#3760]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

**Environment:**
 - Proxmox 8.2.4
 - Proxmox Kernel 6.5.13-5-pve (this is a pinned version)
 - Frigate Version 0.14.1

**Issue Seen:**
The install script is completing ok. But I am getting an error that the Coral USB is not detected in the LXC.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

See detail below. I have tried this running with privileged mode enabled, I get the same issue.

### Please provide detailed steps to reproduce the issue.

**Steps completed outside of script:**
1. On proxmox host, followed steps below to add Coral support (https://coral.ai/docs/accelerator/get-started/)
2. run lsusb - confirming presence of Coral device

**Issue:**
I'm deploying Frigate using the current script version, using the defaults. I then paste in the following basic config to Frigate

```
mqtt:
  enabled: false
cameras:
  Driveway:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://{ip-addr}:8554/Driveway?mp4
          roles:
            - detect
            - rtmp
    detect:
      height: 1080
      width: 1920
      fps: 5

detectors:
  coral:
    type: edgetpu
    device: usb
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
version: 0.14

go2rtc:
  streams:
    Driveway:
      - rtsp://{username}:{pwd}@{ip-addr}/cam/realmonitor?channel=1&subtype=0
    Bins:
      - rtsp://{username}:{pwd}@{ip-addr}/cam/realmonitor?channel=1&subtype=0
    Bikes:
      - rtsp://{username}:{pwd}@{ip-addr}/cam/realmonitor?channel=1&subtype=0
    Garden:
      - rtsp://{username}:{pwd}@{ip-addr}/cam/realmonitor?channel=1&subtype=0`
```

    
**Error seen:**
Logon to Frigate, check logs and I can see the following:
`No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.`
