### ISSUE TITLE
add InfluxDB and Grafana 

### ISSUE THREAD

**Issue by KinDR007** [tteck/Proxmox#45]
Thanks a lot in advance for a great job.
Is it possible to add installation script for **influxdb** and **grafana**?
big thx

**Comment by tteck** [comment]
As I have never used Grafana or InfluxDB, you'll have to let me know if these work ok. Both installs complete successfully.
_Unfortunately I will be of no help with configuration._ 

**Test Grafana:**
```yaml
bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/grafana.sh)"
```
**Test InfluxDB:**
```yaml
bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/influxdb.sh)"
```

**Comment by tteck** [comment]
Grafana Info,

 `admin` for username and password

`systemctl status grafana-server`

Thats all I know 😉 
I'll add both scripts to the main page when I get conformation everything is good.

**Comment by KinDR007** [comment]
great, 
i worked on it yesterday
 just a little differently 
 docker to set up
maybe will help my script

```
version: '2'
services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - '8086:8086'
      - '8089:8089/udp'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=dbhassio
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    restart: always  
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - KAPACITOR_URL=http://kapacitor:9092
      - KAPACITOR_USERNAME=${INFLUXDB_USERNAME}
      - KAPACITOR_PASSWORD=${INFLUXDB_PASSWORD}      
    links:
     - kapacitor
     - influxdb
     - telegraf
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  kapacitor:
    # https://hub.docker.com/r/library/kapacitor/tags/
    image: kapacitor:latest
    volumes:
      - kapacitor-storage:/var/lib/kapacitor
      - ./kapacitor/config/:/etc/kapacitor/
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '9092:9092'
    restart: always

  telegraf:
    # https://hub.docker.com/r/library/telegraf/tags/
    image: telegraf
    environment:
      HOSTNAME: "docker"
    volumes:
      - ./telegraf/:/etc/telegraf/
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb
    depends_on:
      - influxdb
    restart: always



volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
  kapacitor-storage:
```
