### ISSUE TITLE
Automate bind mount config before running LXC containers

### ISSUE THREAD

**Issue by sandreas** [tteck/Proxmox#791]
When I try to use a script that I plan to use a bind mount for integrating external data and adding some lxc user mappings, sometimes it is not possible to configure this before I start the container.

Example:
On [navidrome-v4.sh](https://github.com/tteck/Proxmox/blob/main/ct/navidrome-v4.sh) I would like to have 2 bind mounts in my `/etc/pve/lxc/100.conf`:

```yml
mp0: /rpool/data/shared/audio/music,mp=/music
mp1: /rpool/data/shared/config/navidrome,mp=/var/lib/navidrome
lxc.idmap: u 0 100000 1000
lxc.idmap: g 0 100000 1000
lxc.idmap: u 1000 1000 1
lxc.idmap: g 1000 1000 1
lxc.idmap: u 1001 101001 64435
lxc.idmap: g 1001 101001 64435
```

The reason for this is, that I would like to backup my navidrome config without backing up the whole container, but only the navidrome database. Unfortunately it is not possible to select these mount points in the script... 

The steps I have to take are the following (if SSH is not configured for the container):

1. install the script from tteck (container automatically starts)
2. login into container console and copy `/var/lib/navidrome/` to another directory (e.g. `/root/navidrome/`)
3. stop container and restart with my desired mount points
4. login into container console and copy  `/root/navidrome/` back to `/var/lib/navidrome/` (onto the host system via mount point)

Same problem applies to other containers that use data directories that may be shared over multiple containers (e.g. Photoprism, etc.). Is there a way to configure these kind of mount points / lxc mappings before the container starts the first time to avoid the manual steps I had to perform?
